# Generated by Django 2.0 on 2017-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=6)),
                ('name_EN', models.CharField(max_length=40)),
                ('name_PL', models.CharField(max_length=40)),
                ('ink_type', models.CharField(choices=[('St', 'Standard'), ('IG', 'Iron-Gal')], max_length=8)),
            ],
        ),
    ]
